import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import getServerTheme from "@/hooks/use-server-dark-mode";
import CookiesProviderClient from "@/components/cookies-provider-client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
      template: "%s | Finance App",
      default: "Finance App",
  },
  description: "Generated by create next app",
};

const RootLayout = async ({ children, }: Readonly<{ children: React.ReactNode; }>) =>
{
    const theme = await getServerTheme();

    return (
    <html lang="en" className={theme}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col px-8 antialiased container mx-auto max-w-4xl bg-white text-black dark:bg-slate-950 dark:text-slate-100`}
      >
        <CookiesProviderClient>
            {children}
        </CookiesProviderClient>
      </body>
    </html>
    );
}

export default RootLayout;